import GoogleProvider from "next-auth/providers/google";
import { DefaultSession, NextAuthOptions, Session, } from "next-auth";
import { authService } from "@/services/authService";

declare module "next-auth" {
    interface User {
        role?: string;
        isVerified?: boolean;
        completed?: boolean;
    }
    interface Session {
        user: {
            id: string;
            role?: string; 
            isVerified?: boolean;
            completed?: boolean;
        } & DefaultSession["user"]
    }
    interface JWT {
        id?: string;
        role?: string;
        isVerified?: boolean;
        completed?: boolean;
    }
}

export const authOptions: NextAuthOptions = {
    providers: [
        GoogleProvider({
            clientId: process.env.GOOGLE_CLIENT_ID!,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
        })
    ],
    
    session: {
        strategy:"jwt",
        maxAge: 30 * 24 * 60 * 60,
    },

   callbacks: {
     async signIn({ profile, user }) {
       if (!profile?.sub || !user?.email) return false;
       return true;
     },

    async jwt({ token, user, profile, trigger }) {
      if (profile?.sub && user?.email) {
        try{
        const dbUser = await authService.findOrCreateGoogleUser(
          { sub: profile.sub, email: profile.email! },
          { name: user.name!, email: user.email }
        );

        token.id = dbUser.id;
        token.role = dbUser.role;
        token.completed = dbUser.is_completed;
      } catch (error) {
         console.error("JWT callback error:", error);
         return token;
        }
      }
      if (trigger === "update" && token.id) {
         try {
           const updatedUser = await authService.getUserById(token.id as string);
           if (updatedUser) {
             token.completed = updatedUser.is_completed;
             token.role = updatedUser.role;
           }
         } catch (error) {
          console.error("Token update error:", error);
         }
       }
  
       return token;
    },

  async session({ session, token }) {
    if (session.user) {
      session.user.id = token.id as string;
      session.user.role = token.role as string | undefined;
      session.user.completed = token.completed as boolean | undefined;
    }
    return session;
  },

  async redirect({ baseUrl }) {
    return `${baseUrl}/dashboard`;
  }
},


}
    // secret:  if we need tokens start generated by any secerts ...
    // pages:{
    //     signIn: '/signup',
    //     newUser:'welcom'
    // }

// console.log({
//   id: process.env.GOOGLE_CLIENT_ID,
//   secret: process.env.GOOGLE_CLIENT_SECRET,
// });
