// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ReduxProvider } from './providers/reduxProvider';
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Yasser's Laundry",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} h-full`}>
//         <ReduxProvider>
//         {children}
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }
import './globals.css';
import Providers  from './providers/reduxProvider';
import { Toaster } from 'react-hot-toast';
export const metadata = {
  title: "Yasser's Laundry",
  description: 'Laundry App',
   icons: {
    icon: '/favicon.webp',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Toaster
          position="top-center"
          toastOptions={{
            duration: 5000,
            style: {
              fontSize: '10px',
              borderRadius: '50px',
            },
          }}
        />
        </Providers>
        
      </body>
    </html>
  );
}
